### ISSUE TITLE
Update Anthropic Client 

### ISSUE THREAD

**Issue by krrishdholakia** [jw782cn/MyClaude#1]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/jw782cn/MyClaude/blob/1697d26c509f979c9aaa6a65351584a568fbcbc3/config.py#L21

Would love to know if this might help - https://github.com/BerriAI/litellm

~Simple I/O library, that standardizes all the llm api calls to the OpenAI call

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)

```

**Comment by krrishdholakia** [comment]
cc: @jw782cn

**Comment by jw782cn** [comment]
Happy to see you point out. However, i tested again, seems current version still works. I guess because I didn't use claude client version / python SDK. I will try litellm in my next project~
